name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: book_store
        ports: ['3306:3306']
    env:
      DB_DATABASE: book_store
      DB_USER: root
      DB_PASSWORD: password
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Install code sniffer
      run: composer require "squizlabs/php_codesniffer=*"
    - name: run phpcs
      run: vendor/bin/phpcs .
    - name: Run migration
      run: php artisan migrate
    - name: Run seeder
      run: php artisan db:seed
    - name: Execute tests
      run: vendor/bin/phpunit --coverage-text

